`ifdef ST_WIDTH_INF_2
$fwrite(tr_report, "===============================%d Comp Results    ======================================\n",mem_index);
if(error_percent_r0  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item0   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r0  , golden_real_r0  , dut_real_r0  ); end else begin $fwrite(tr_report, "Item0   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r0  , golden_real_r0  , dut_real_r0  ); end
if(error_percent_r1  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item1   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r1  , golden_real_r1  , dut_real_r1  ); end else begin $fwrite(tr_report, "Item1   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r1  , golden_real_r1  , dut_real_r1  ); end
if(error_percent_i0  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item0   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i0  , golden_real_i0  , dut_real_i0  ); end else begin $fwrite(tr_report, "Item0   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i0  , golden_real_i0  , dut_real_i0  ); end
if(error_percent_i1  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item1   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i1  , golden_real_i1  , dut_real_i1  ); end else begin $fwrite(tr_report, "Item1   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i1  , golden_real_i1  , dut_real_i1  ); end
`endif // ST_WIDTH_INF_2
`ifdef ST_WIDTH_INF_4
if(error_percent_r2  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item2   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r2  , golden_real_r2  , dut_real_r2  ); end else begin $fwrite(tr_report, "Item2   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r2  , golden_real_r2  , dut_real_r2  ); end
if(error_percent_r3  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item3   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r3  , golden_real_r3  , dut_real_r3  ); end else begin $fwrite(tr_report, "Item3   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r3  , golden_real_r3  , dut_real_r3  ); end
if(error_percent_i2  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item2   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i2  , golden_real_i2  , dut_real_i2  ); end else begin $fwrite(tr_report, "Item2   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i2  , golden_real_i2  , dut_real_i2  ); end
if(error_percent_i3  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item3   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i3  , golden_real_i3  , dut_real_i3  ); end else begin $fwrite(tr_report, "Item3   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i3  , golden_real_i3  , dut_real_i3  ); end
`endif // ST_WIDTH_INF_4
`ifdef ST_WIDTH_INF_16
if(error_percent_r4  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item4   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r4  , golden_real_r4  , dut_real_r4  ); end else begin $fwrite(tr_report, "Item4   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r4  , golden_real_r4  , dut_real_r4  ); end
if(error_percent_r5  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item5   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r5  , golden_real_r5  , dut_real_r5  ); end else begin $fwrite(tr_report, "Item5   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r5  , golden_real_r5  , dut_real_r5  ); end
if(error_percent_r6  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item6   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r6  , golden_real_r6  , dut_real_r6  ); end else begin $fwrite(tr_report, "Item6   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r6  , golden_real_r6  , dut_real_r6  ); end
if(error_percent_r7  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item7   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r7  , golden_real_r7  , dut_real_r7  ); end else begin $fwrite(tr_report, "Item7   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r7  , golden_real_r7  , dut_real_r7  ); end
if(error_percent_r8  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item8   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r8  , golden_real_r8  , dut_real_r8  ); end else begin $fwrite(tr_report, "Item8   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r8  , golden_real_r8  , dut_real_r8  ); end
if(error_percent_r9  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item9   Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r9  , golden_real_r9  , dut_real_r9  ); end else begin $fwrite(tr_report, "Item9   Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r9  , golden_real_r9  , dut_real_r9  ); end
if(error_percent_r10 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item10  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r10 , golden_real_r10 , dut_real_r10 ); end else begin $fwrite(tr_report, "Item10  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r10 , golden_real_r10 , dut_real_r10 ); end
if(error_percent_r11 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item11  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r11 , golden_real_r11 , dut_real_r11 ); end else begin $fwrite(tr_report, "Item11  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r11 , golden_real_r11 , dut_real_r11 ); end
if(error_percent_r12 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item12  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r12 , golden_real_r12 , dut_real_r12 ); end else begin $fwrite(tr_report, "Item12  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r12 , golden_real_r12 , dut_real_r12 ); end
if(error_percent_r13 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item13  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r13 , golden_real_r13 , dut_real_r13 ); end else begin $fwrite(tr_report, "Item13  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r13 , golden_real_r13 , dut_real_r13 ); end
if(error_percent_r14 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item14  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r14 , golden_real_r14 , dut_real_r14 ); end else begin $fwrite(tr_report, "Item14  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r14 , golden_real_r14 , dut_real_r14 ); end
if(error_percent_r15 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item15  Comp Pass! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r15 , golden_real_r15 , dut_real_r15 ); end else begin $fwrite(tr_report, "Item15  Comp FAIL! error percent_r: %f%%, golden result: %f, dut result: %f\n", error_percent_r15 , golden_real_r15 , dut_real_r15 ); end
if(error_percent_i4  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item4   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i4  , golden_real_i4  , dut_real_i4  ); end else begin $fwrite(tr_report, "Item4   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i4  , golden_real_i4  , dut_real_i4  ); end
if(error_percent_i5  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item5   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i5  , golden_real_i5  , dut_real_i5  ); end else begin $fwrite(tr_report, "Item5   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i5  , golden_real_i5  , dut_real_i5  ); end
if(error_percent_i6  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item6   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i6  , golden_real_i6  , dut_real_i6  ); end else begin $fwrite(tr_report, "Item6   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i6  , golden_real_i6  , dut_real_i6  ); end
if(error_percent_i7  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item7   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i7  , golden_real_i7  , dut_real_i7  ); end else begin $fwrite(tr_report, "Item7   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i7  , golden_real_i7  , dut_real_i7  ); end
if(error_percent_i8  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item8   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i8  , golden_real_i8  , dut_real_i8  ); end else begin $fwrite(tr_report, "Item8   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i8  , golden_real_i8  , dut_real_i8  ); end
if(error_percent_i9  <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item9   Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i9  , golden_real_i9  , dut_real_i9  ); end else begin $fwrite(tr_report, "Item9   Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i9  , golden_real_i9  , dut_real_i9  ); end
if(error_percent_i10 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item10  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i10 , golden_real_i10 , dut_real_i10 ); end else begin $fwrite(tr_report, "Item10  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i10 , golden_real_i10 , dut_real_i10 ); end
if(error_percent_i11 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item11  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i11 , golden_real_i11 , dut_real_i11 ); end else begin $fwrite(tr_report, "Item11  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i11 , golden_real_i11 , dut_real_i11 ); end
if(error_percent_i12 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item12  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i12 , golden_real_i12 , dut_real_i12 ); end else begin $fwrite(tr_report, "Item12  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i12 , golden_real_i12 , dut_real_i12 ); end
if(error_percent_i13 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item13  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i13 , golden_real_i13 , dut_real_i13 ); end else begin $fwrite(tr_report, "Item13  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i13 , golden_real_i13 , dut_real_i13 ); end
if(error_percent_i14 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item14  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i14 , golden_real_i14 , dut_real_i14 ); end else begin $fwrite(tr_report, "Item14  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i14 , golden_real_i14 , dut_real_i14 ); end
if(error_percent_i15 <=`ERROR_THRESHOLD) begin $fwrite(tr_report, "Item15  Comp Pass! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i15 , golden_real_i15 , dut_real_i15 ); end else begin $fwrite(tr_report, "Item15  Comp FAIL! error percent_i: %f%%, golden result: %f, dut result: %f\n", error_percent_i15 , golden_real_i15 , dut_real_i15 ); end
`endif // ST_WIDTH_INF_16
