// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module fsm(	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
  input         clk,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:29:17
                rst,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:30:17
                tsqr_en,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:31:21
  input  [15:0] tile_no,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:32:21
  output [15:0] hh_cnt,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:33:20
                mx_cnt,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:34:20
  output        d1_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:35:20
                d1_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:36:20
                d2_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:37:20
                d2_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:38:20
                vk1_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:39:21
                vk1_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:40:21
                d3_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:41:20
                d3_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:42:20
                tk_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:43:20
                tk_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:44:20
                d4_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:45:20
                d4_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:46:20
                d5_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:47:20
                d5_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:48:20
                yjp_rdy,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:49:21
                yjp_vld,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:50:21
                yj_sft,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:51:20
                d4_sft,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:52:20
                hh_st,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:53:19
                mem0_fi,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:54:21
                mem1_fi,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:55:21
                tsqr_fi,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:56:21
                dmx0_mem_ena,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:57:26
  output [63:0] dmx0_mem_wea,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:58:26
  output [2:0]  dmx0_mem_addra,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:59:28
  output        dmx0_mem_enb,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:60:26
  output [2:0]  dmx0_mem_addrb,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:61:28
  output        dmx1_mem_ena,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:62:26
  output [63:0] dmx1_mem_wea,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:63:26
  output [2:0]  dmx1_mem_addra,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:64:28
  output        dmx1_mem_enb,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:65:26
  output [2:0]  dmx1_mem_addrb,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:66:28
  output        rtri_mem_ena,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:67:26
  output [63:0] rtri_mem_wea,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:68:26
  output [2:0]  rtri_mem_addra,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:69:28
  output        rtri_mem_enb,	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:70:26
  output [2:0]  rtri_mem_addrb	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:71:28
);

  reg         hh_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24
  reg         nxt_hh_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:92:28
  reg  [15:0] cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22
  reg  [15:0] nxt_hh_cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:110:29
  reg  [15:0] nxt_mx_cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:111:29
  wire [15:0] _hh_cnt_output = rst ? 16'h0 : nxt_hh_cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:110:29, :114:21, :137:18, :139:20, :143:20
  wire [15:0] _mx_cnt_output = rst ? 16'h0 : nxt_mx_cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:111:29, :114:21, :137:18, :140:20, :144:20
  reg  [15:0] tr_cy_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:147:28
  reg         tr_cnt_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:148:28
  reg  [15:0] tr_cnt;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25
  wire        wr_mem_st = ~rst & hh_en & tr_cnt == 16'h1A;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :149:25, :154:18, :155:24, :156:23, :160:24, :161:{23,42}
  wire        rd_mem_st = ~rst & hh_en & cnt == 16'h23;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :108:22, :154:18, :155:24, :158:23, :160:24, :163:{23,39}
  wire [15:0] _tr_cy_T = 16'h8 - _hh_cnt_output;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :170:45
  wire [15:0] tr_cy = rd_mem_st ? _tr_cy_T : tr_cy_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:147:28, :154:18, :158:23, :163:23, :169:24, :170:{19,45}, :172:19
  reg         tr_cnt_en_2;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:202:30
  reg         d1_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:219:26
  reg         d1_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:220:26
  reg         d2_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:221:26
  reg         d2_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:222:26
  reg         vk1_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:223:27
  reg         vk1_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:224:27
  reg         d3_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:225:26
  reg         d3_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:226:26
  reg         tk_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:227:26
  reg         tk_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:228:26
  reg         yj_sft_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:245:25
  reg         dmx0_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:253:35
  reg         dmx1_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:254:35
  reg         rtri_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:255:35
  reg         dmx0_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:256:35
  reg         dmx1_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:257:35
  reg         rtri_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:258:35
  reg  [2:0]  dmx0_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:279:37
  reg  [2:0]  dmx1_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:280:37
  reg  [2:0]  rtri_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:281:37
  reg  [63:0] dmx0_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:319:35
  reg  [63:0] dmx1_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:320:35
  reg  [63:0] rtri_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:321:35
  reg  [63:0] rtri_mem_wea_update;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:324:38
  wire        _GEN = ~(_mx_cnt_output[0]) & wr_mem_st;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :154:18, :156:23, :161:23, :336:{15,22,34}
  wire        _GEN_0 = _mx_cnt_output[0] & wr_mem_st;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :154:18, :156:23, :161:23, :336:22, :342:24
  reg  [2:0]  dmx0_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:364:37
  reg  [2:0]  dmx1_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:365:37
  reg  [2:0]  rtri_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:366:37
  wire        _mem1_fi_T_7 = tr_cy == 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:169:24, :170:19, :172:19, :219:38, :427:89
  wire        _mem0_fi_output =
    ~(_mx_cnt_output[0]) & tr_cnt == tr_cy + 16'h1A & _mem1_fi_T_7;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :149:25, :161:42, :169:24, :170:19, :172:19, :336:22, :427:{16,45,72,80,89}
  wire        _mem1_fi_output =
    _mx_cnt_output[0] & tr_cnt == tr_cy + 16'h1A & _mem1_fi_T_7;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :149:25, :161:42, :169:24, :170:19, :172:19, :336:22, :427:89, :428:{34,61,68}
  always @(posedge clk) begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:29:17
    automatic logic _GEN_1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:113:18
    automatic logic _GEN_2;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:121:42
    automatic logic hh_fi;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:176:26
    automatic logic _GEN_3;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:199:27
    automatic logic _GEN_4;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:195:18, :196:23, :197:26, :198:23, :199:51
    automatic logic _d2_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:220:40
    automatic logic _vk1_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:222:40
    automatic logic _d3_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:224:41
    automatic logic _tk_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:226:40
    _GEN_1 = cnt == 16'h45;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :113:18
    _GEN_2 = _hh_cnt_output == 16'h7;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:121:42, :137:18, :139:20, :143:20
    hh_fi = tr_cnt == tr_cy + 16'h1C;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25, :169:24, :170:19, :172:19, :176:{26,53}
    _GEN_3 = hh_en & cnt == 16'h28;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :108:22, :199:{27,34}
    _GEN_4 = rst | hh_fi;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:176:26, :195:18, :196:23, :197:26, :198:23, :199:51
    _d2_rdy_T = cnt == 16'h6;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :220:40
    _vk1_rdy_T = cnt == 16'h9;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :222:40
    _d3_rdy_T = cnt == 16'h25;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :224:41
    _tk_rdy_T = cnt == 16'h2B;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :226:40
    if (rst) begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:29:17
      hh_en <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :95:23
      cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :114:21
      tr_cy_reg <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:114:21, :147:28
      tr_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:114:21, :149:25
      dmx0_mem_enb_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :253:35
      dmx1_mem_enb_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :254:35
      rtri_mem_enb_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :255:35
      dmx0_mem_ena_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :256:35
      dmx1_mem_ena_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :257:35
      rtri_mem_ena_reg <= 1'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:95:23, :258:35
      dmx0_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:279:37, :290:33
      dmx1_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:280:37, :290:33
      rtri_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:281:37, :290:33
      dmx0_mem_wea_reg <= 64'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:319:35, :355:30
      dmx1_mem_wea_reg <= 64'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:320:35, :355:30
      rtri_mem_wea_reg <= 64'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:321:35, :355:30
      rtri_mem_wea_update <= 64'hFFFFFFFFFFFFFFFF;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:324:38, :433:32
      dmx0_mem_addra_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:290:33, :364:37
      dmx1_mem_addra_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:290:33, :365:37
      rtri_mem_addra_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:290:33, :366:37
    end
    else begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:29:17
      automatic logic        rd_mem_fst;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :155:24, :160:24
      automatic logic [15:0] _mem1_fi_T_1 = tr_cy + 16'h1B;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:169:24, :170:19, :172:19, :176:45, :331:64
      automatic logic        _rd_rtri_en_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:271:54
      automatic logic        rd_dmx0_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :264:24, :271:24
      automatic logic        rd_dmx1_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :265:24, :272:24
      automatic logic        rd_rtri_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :266:24, :273:24
      automatic logic        _rtri_mem_ena_wire_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:331:64
      automatic logic        dmx0_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :327:31, :331:31
      automatic logic        dmx1_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :328:31, :332:31
      automatic logic        rtri_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :329:31, :333:31
      automatic logic        _GEN_5;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:368:43
      rd_mem_fst = ~rst & (tsqr_en & ~hh_en | ~nxt_hh_en);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :92:28, :154:18, :155:24, :160:{24,36,39,54,57}
      _rd_rtri_en_T = cnt > 16'h24;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :271:54
      rd_dmx0_en = ~rst & ~(_mx_cnt_output[0]) & _rd_rtri_en_T & cnt < tr_cy + 16'h26;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :137:18, :140:20, :144:20, :154:18, :155:24, :160:24, :169:24, :170:19, :172:19, :263:18, :264:24, :271:{24,28,35,54,73,93}
      rd_dmx1_en = ~rst & _mx_cnt_output[0] & _rd_rtri_en_T & cnt < tr_cy + 16'h26;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :137:18, :140:20, :144:20, :154:18, :155:24, :160:24, :169:24, :170:19, :172:19, :263:18, :265:24, :271:{35,54,93}, :272:{24,63,84}
      rd_rtri_en = ~rst & _rd_rtri_en_T & cnt < tr_cy + 16'h26;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :154:18, :155:24, :160:24, :169:24, :170:19, :172:19, :263:18, :266:24, :271:{54,93}, :273:{24,51,71}
      _rtri_mem_ena_wire_T = tr_cnt > 16'h1A;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25, :161:42, :331:64
      dmx0_mem_ena_wire =
        ~rst & ~(_mx_cnt_output[0]) & _rtri_mem_ena_wire_T & tr_cnt < _mem1_fi_T_1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :149:25, :154:18, :155:24, :160:24, :176:45, :326:18, :327:31, :331:{31,35,42,64,94}
      dmx1_mem_ena_wire =
        ~rst & _mx_cnt_output[0] & _rtri_mem_ena_wire_T & tr_cnt < _mem1_fi_T_1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :149:25, :154:18, :155:24, :160:24, :176:45, :326:18, :328:31, :331:{42,64}, :332:{31,84}
      rtri_mem_ena_wire = ~rst & _rtri_mem_ena_wire_T & tr_cnt < _mem1_fi_T_1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25, :154:18, :155:24, :160:24, :176:45, :326:18, :329:31, :331:64, :333:{31,72}
      _GEN_5 = hh_en & tr_cnt == 16'h1B;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :149:25, :331:64, :368:{43,53}
      hh_en <= nxt_hh_en;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :92:28
      if (_GEN_1)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:113:18
        cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :114:21
      else if (hh_en)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24
        cnt <= cnt + 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :116:28, :219:38
      if (rd_mem_st)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :158:23, :163:23
        tr_cy_reg <= _tr_cy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:147:28, :170:45
      if (hh_fi)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:176:26
        tr_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:114:21, :149:25
      else if (tr_cnt_en)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:148:28
        tr_cnt <= tr_cnt + 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25, :182:34, :219:38
      dmx0_mem_enb_reg <= ~rst & (~(_mx_cnt_output[0]) & rd_mem_fst | rd_dmx0_en);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :154:18, :155:24, :160:24, :253:35, :263:18, :264:24, :267:31, :271:{24,35}, :274:{31,36,55,72}
      dmx1_mem_enb_reg <= ~rst & (_mx_cnt_output[0] & rd_mem_fst | rd_dmx1_en);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :154:18, :155:24, :160:24, :254:35, :263:18, :265:24, :268:31, :271:35, :272:24, :275:{31,45,61}
      rtri_mem_enb_reg <= ~rst & (rd_mem_fst | rd_rtri_en);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :155:24, :160:24, :255:35, :263:18, :266:24, :269:31, :273:24, :276:{31,45}
      dmx0_mem_ena_reg <= dmx0_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:256:35, :326:18, :327:31, :331:31
      dmx1_mem_ena_reg <= dmx1_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:257:35, :326:18, :328:31, :332:31
      rtri_mem_ena_reg <= rtri_mem_ena_wire;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:258:35, :326:18, :329:31, :333:31
      if (rd_mem_fst) begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :155:24, :160:24
        dmx0_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:279:37, :290:33
        dmx1_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:280:37, :290:33
        rtri_mem_addrb_reg <= 3'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:281:37, :290:33
      end
      else begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :155:24, :160:24
        automatic logic _GEN_6;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:291:49
        _GEN_6 = hh_en & _d3_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :224:41, :291:49
        if (~(_mx_cnt_output[0]) & _GEN_6)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :291:{21,28,40,49}
          dmx0_mem_addrb_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :279:37, :292:32
        else if (rd_dmx0_en)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :264:24, :271:24
          dmx0_mem_addrb_reg <= dmx0_mem_addrb_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:279:37, :294:55
        if (_mx_cnt_output[0] & _GEN_6)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :291:{28,49}, :301:30
          dmx1_mem_addrb_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :280:37, :292:32
        else if (rd_dmx1_en)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :265:24, :272:24
          dmx1_mem_addrb_reg <= dmx1_mem_addrb_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:280:37, :294:55, :304:55
        if (_GEN_6)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:291:49
          rtri_mem_addrb_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :281:37, :292:32
        else if (rd_rtri_en)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:263:18, :266:24, :273:24
          rtri_mem_addrb_reg <= rtri_mem_addrb_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:281:37, :294:55, :314:55
      end
      if (_GEN)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:336:34
        dmx0_mem_wea_reg <= 64'hFFFFFFFFFFFFFFFF;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:319:35, :433:32
      if (_GEN_0)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:342:24
        dmx1_mem_wea_reg <= 64'hFFFFFFFFFFFFFFFF;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:320:35, :433:32
      if (wr_mem_st)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:154:18, :156:23, :161:23
        rtri_mem_wea_reg <= rtri_mem_wea_update;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:321:35, :324:38
      if (hh_en & tr_cnt == 16'h19)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :149:25, :436:{22,32}
        rtri_mem_wea_update <= rtri_mem_wea_update >> {45'h0, _hh_cnt_output, 3'h0};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :290:33, :324:38, :437:52
      else	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:436:22
        rtri_mem_wea_update <= 64'hFFFFFFFFFFFFFFFF;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:324:38, :433:32
      if (~(_mx_cnt_output[0]) & _GEN_5)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :336:{15,22}, :368:{34,43}
        dmx0_mem_addra_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :292:32, :364:37
      else if (dmx0_mem_ena_wire)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :327:31, :331:31
        dmx0_mem_addra_reg <= dmx0_mem_addra_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:294:55, :364:37, :371:55
      if (_mx_cnt_output[0] & _GEN_5)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :140:20, :144:20, :336:22, :368:43, :376:24
        dmx1_mem_addra_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :292:32, :365:37
      else if (dmx1_mem_ena_wire)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :328:31, :332:31
        dmx1_mem_addra_reg <= dmx1_mem_addra_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:294:55, :365:37, :379:55
      if (_GEN_5)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:368:43
        rtri_mem_addra_reg <= _hh_cnt_output[2:0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:137:18, :139:20, :143:20, :292:32, :366:37
      else if (rtri_mem_ena_wire)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:326:18, :329:31, :333:31
        rtri_mem_addra_reg <= rtri_mem_addra_reg + 3'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:294:55, :366:37, :387:55
    end
    nxt_hh_en <= ~(rst | _mem0_fi_output | _mem1_fi_output) & (tsqr_en | nxt_hh_en);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:92:28, :94:18, :95:23, :96:38, :97:23, :98:28, :99:23, :427:80, :428:68
    if (_GEN_1 & _GEN_2)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:113:18, :121:{33,42}
      nxt_hh_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:110:29, :114:21
    else if (hh_en & _GEN_1)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :113:18, :123:26
      nxt_hh_cnt <= _hh_cnt_output + 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:110:29, :124:34, :137:18, :139:20, :143:20, :219:38
    else if (rst)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:30:17
      nxt_hh_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:110:29, :114:21
    if (_GEN_2 & _mx_cnt_output == tile_no & _GEN_1)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:113:18, :121:42, :129:{59,74}, :137:18, :140:20, :144:20
      nxt_mx_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:111:29, :114:21
    else if (_GEN_2 & cnt == 16'h44)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:108:22, :121:42, :131:{57,63}
      nxt_mx_cnt <= _mx_cnt_output + 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:111:29, :132:34, :137:18, :140:20, :144:20, :219:38
    else if (rst)	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:30:17
      nxt_mx_cnt <= 16'h0;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:111:29, :114:21
    tr_cnt_en <= ~_GEN_4 & (_GEN_3 | ~_GEN_4 & (_GEN_3 | tr_cnt_en));	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:148:28, :195:18, :196:23, :197:26, :198:23, :199:{27,51}, :200:23, :204:18, :205:23, :206:26, :207:23, :208:51, :209:23
    tr_cnt_en_2 <= ~_GEN_4 & (hh_en & cnt == 16'h27 | tr_cnt_en_2);	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :108:22, :195:18, :196:23, :197:26, :198:23, :199:51, :202:30, :211:18, :212:25, :213:26, :214:25, :215:{27,34,51}, :216:25
    d1_rdy_REG <= hh_en & cnt == 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :108:22, :219:{26,33,38}
    d1_vld_REG <= hh_en & _d2_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :220:{26,33,40}
    d2_rdy_REG <= hh_en & _d2_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :220:40, :221:{26,33}
    d2_vld_REG <= hh_en & _vk1_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :222:{26,33,40}
    vk1_rdy_REG <= hh_en & _vk1_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :222:40, :223:{27,34}
    vk1_vld_REG <= hh_en & _d3_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :224:{27,34,41}
    d3_rdy_REG <= hh_en & _d3_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :224:41, :225:{26,33}
    d3_vld_REG <= hh_en & _tk_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :226:{26,33,40}
    tk_rdy_REG <= hh_en & _tk_rdy_T;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :226:40, :227:{26,33}
    tk_vld_REG <= hh_en & cnt == 16'h3B;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:91:24, :108:22, :228:{26,33,40}
    yj_sft_REG <= tr_cnt_en_2 & tr_cnt < tr_cy + 16'h18;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:149:25, :169:24, :170:19, :172:19, :202:30, :245:{25,38,48,72}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
      `FIRRTL_BEFORE_INITIAL	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
      automatic logic [31:0] _RANDOM[0:15];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
        `INIT_RANDOM_PROLOG_	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM[i[3:0]] = `RANDOM;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
        end	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
        hh_en = _RANDOM[4'h0][0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :91:24
        nxt_hh_en = _RANDOM[4'h0][1];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :91:24, :92:28
        cnt = _RANDOM[4'h0][17:2];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :91:24, :108:22
        nxt_hh_cnt = {_RANDOM[4'h0][31:18], _RANDOM[4'h1][1:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :91:24, :110:29
        nxt_mx_cnt = _RANDOM[4'h1][17:2];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :110:29, :111:29
        tr_cy_reg = {_RANDOM[4'h1][31:18], _RANDOM[4'h2][1:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :110:29, :147:28
        tr_cnt_en = _RANDOM[4'h2][2];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :148:28
        tr_cnt = _RANDOM[4'h2][18:3];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :149:25
        tr_cnt_en_2 = _RANDOM[4'h2][19];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :202:30
        d1_rdy_REG = _RANDOM[4'h2][20];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :219:26
        d1_vld_REG = _RANDOM[4'h2][21];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :220:26
        d2_rdy_REG = _RANDOM[4'h2][22];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :221:26
        d2_vld_REG = _RANDOM[4'h2][23];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :222:26
        vk1_rdy_REG = _RANDOM[4'h2][24];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :223:27
        vk1_vld_REG = _RANDOM[4'h2][25];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :224:27
        d3_rdy_REG = _RANDOM[4'h2][26];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :225:26
        d3_vld_REG = _RANDOM[4'h2][27];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :226:26
        tk_rdy_REG = _RANDOM[4'h2][28];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :227:26
        tk_vld_REG = _RANDOM[4'h2][29];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :228:26
        yj_sft_REG = _RANDOM[4'h2][30];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :245:25
        dmx0_mem_enb_reg = _RANDOM[4'h2][31];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :147:28, :253:35
        dmx1_mem_enb_reg = _RANDOM[4'h3][0];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35
        rtri_mem_enb_reg = _RANDOM[4'h3][1];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :255:35
        dmx0_mem_ena_reg = _RANDOM[4'h3][2];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :256:35
        dmx1_mem_ena_reg = _RANDOM[4'h3][3];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :257:35
        rtri_mem_ena_reg = _RANDOM[4'h3][4];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :258:35
        dmx0_mem_addrb_reg = _RANDOM[4'h3][7:5];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :279:37
        dmx1_mem_addrb_reg = _RANDOM[4'h3][10:8];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :280:37
        rtri_mem_addrb_reg = _RANDOM[4'h3][13:11];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :281:37
        dmx0_mem_wea_reg = {_RANDOM[4'h3][31:14], _RANDOM[4'h4], _RANDOM[4'h5][13:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35, :319:35
        dmx1_mem_wea_reg = {_RANDOM[4'h5][31:14], _RANDOM[4'h6], _RANDOM[4'h7][13:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :319:35, :320:35
        rtri_mem_wea_reg = {_RANDOM[4'h7][31:14], _RANDOM[4'h8], _RANDOM[4'h9][13:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :320:35, :321:35
        rtri_mem_wea_update = {_RANDOM[4'hD][31:14], _RANDOM[4'hE], _RANDOM[4'hF][13:0]};	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :324:38
        dmx0_mem_addra_reg = _RANDOM[4'hF][16:14];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :324:38, :364:37
        dmx1_mem_addra_reg = _RANDOM[4'hF][19:17];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :324:38, :365:37
        rtri_mem_addra_reg = _RANDOM[4'hF][22:20];	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :324:38, :366:37
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
      `FIRRTL_AFTER_INITIAL	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign hh_cnt = _hh_cnt_output;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :137:18, :139:20, :143:20
  assign mx_cnt = _mx_cnt_output;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :137:18, :140:20, :144:20
  assign d1_rdy = d1_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :219:26
  assign d1_vld = d1_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :220:26
  assign d2_rdy = d2_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :221:26
  assign d2_vld = d2_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :222:26
  assign vk1_rdy = vk1_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :223:27
  assign vk1_vld = vk1_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :224:27
  assign d3_rdy = d3_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :225:26
  assign d3_vld = d3_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :226:26
  assign tk_rdy = tk_rdy_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :227:26
  assign tk_vld = tk_vld_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :228:26
  assign d4_rdy = tr_cnt_en & tr_cnt < tr_cy;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :230:{29,39}
  assign d4_vld = tr_cnt_en & tr_cnt > 16'h5 & tr_cnt < tr_cy + 16'h6;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :220:40, :231:{39,55,65,78}, :243:39
  assign d5_rdy = tr_cnt_en & tr_cnt > 16'h2 & tr_cnt < tr_cy + 16'h13;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :236:{39,76,86,122}
  assign d5_vld =
    tr_cnt_en & tr_cnt >= tr_cy + 16'h17 - tr_cy - 16'h1 & tr_cnt < tr_cy + 16'h16;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :234:{39,75,87,95,103,113,153}
  assign yjp_rdy = tr_cnt_en & tr_cnt > 16'h6 & tr_cnt < tr_cy + 16'h17;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :220:40, :234:75, :240:{40,83,93,128}
  assign yjp_vld = tr_cnt_en & tr_cnt < tr_cy + 16'h1A & tr_cnt > 16'h9;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :161:42, :169:24, :170:19, :172:19, :222:40, :241:{40,88,102,112}
  assign yj_sft = yj_sft_REG;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :245:25
  assign d4_sft = tr_cnt_en & tr_cnt > 16'h4 & tr_cnt < tr_cy + 16'h14;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :148:28, :149:25, :169:24, :170:19, :172:19, :243:{39,57,67,94}
  assign hh_st = ~rst & hh_en & tr_cnt == 16'h1E;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :91:24, :149:25, :154:18, :155:24, :157:19, :160:24, :162:{19,38}
  assign mem0_fi = _mem0_fi_output;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :427:80
  assign mem1_fi = _mem1_fi_output;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :428:68
  assign tsqr_fi =
    (_mem0_fi_output | _mem1_fi_output) & _mx_cnt_output == tile_no - 16'h1;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :137:18, :140:20, :144:20, :427:80, :428:68, :430:{25,36,46,58}
  assign dmx0_mem_ena = dmx0_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :256:35
  assign dmx0_mem_wea = _GEN ? 64'hFFFFFFFFFFFFFFFF : dmx0_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :319:35, :336:{34,46}, :337:26, :339:26, :433:32
  assign dmx0_mem_addra = dmx0_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :364:37
  assign dmx0_mem_enb = dmx0_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :253:35
  assign dmx0_mem_addrb = dmx0_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :279:37
  assign dmx1_mem_ena = dmx1_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :257:35
  assign dmx1_mem_wea = _GEN_0 ? 64'hFFFFFFFFFFFFFFFF : dmx1_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :320:35, :342:{24,36}, :343:26, :345:26, :433:32
  assign dmx1_mem_addra = dmx1_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :365:37
  assign dmx1_mem_enb = dmx1_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :254:35
  assign dmx1_mem_addrb = dmx1_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :280:37
  assign rtri_mem_ena = rtri_mem_ena_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :258:35
  assign rtri_mem_wea = wr_mem_st ? rtri_mem_wea_update : rtri_mem_wea_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :154:18, :156:23, :161:23, :321:35, :324:38, :348:24, :349:26, :351:26
  assign rtri_mem_addra = rtri_mem_addra_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :366:37
  assign rtri_mem_enb = rtri_mem_enb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :255:35
  assign rtri_mem_addrb = rtri_mem_addrb_reg;	// C:\\TSQR-Factorization-Design-with-Chisel-HCL\\src\\main\\scala\\tsqr_fsm.scala:27:7, :281:37
endmodule


