// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module full_subtractor(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9
  input  [7:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
               io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output [7:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output       io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
);

  wire [8:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:100:23
  assign io_out_s = result[7:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :101:23
  assign io_out_c = result[8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :102:23
endmodule

module full_adder(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9
  input  [23:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output [23:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output        io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
);

  wire [24:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:86:23
  assign io_out_s = result[23:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :87:23
  assign io_out_c = result[24];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :88:23
endmodule

module LZC_enc2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:7:9
  input  [1:0] io_in_r,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:8:16
  output [1:0] io_out_e	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:8:16
);

  assign io_out_e = io_in_r == 2'h0 ? 2'h2 : {1'h0, io_in_r == 2'h1};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:7:9, :23:48, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

module LZC_Merge2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [1:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [2:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[1] & io_in_l[1],
     io_in_h[1] ? ~(io_in_l[1]) : io_in_h[1],
     io_in_h[1] ? io_in_l[0] : io_in_h[0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge3(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [2:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [3:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[2] & io_in_l[2],
     io_in_h[2] ? ~(io_in_l[2]) : io_in_h[2],
     io_in_h[2] ? io_in_l[1:0] : io_in_h[1:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge4(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [3:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [4:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[3] & io_in_l[3],
     io_in_h[3] ? ~(io_in_l[3]) : io_in_h[3],
     io_in_h[3] ? io_in_l[2:0] : io_in_h[2:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge5(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [4:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [5:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[4] & io_in_l[4],
     io_in_h[4] ? ~(io_in_l[4]) : io_in_h[4],
     io_in_h[4] ? io_in_l[3:0] : io_in_h[3:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC32_2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:29:9
  input  [31:0] io_in_d,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:30:16
  output [5:0]  io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:30:16
);

  wire [4:0] _LZC_Merge4_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [4:0] _LZC_Merge4_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_7_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_6_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_5_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_4_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [1:0] _LZC_enc2_15_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_14_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_13_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_12_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_11_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_10_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_9_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_8_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_7_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_6_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_5_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_4_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_3_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_2_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_1_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  LZC_enc2 LZC_enc2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[1:0]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_io_out_e)
  );
  LZC_enc2 LZC_enc2_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[3:2]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_1_io_out_e)
  );
  LZC_enc2 LZC_enc2_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[5:4]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_2_io_out_e)
  );
  LZC_enc2 LZC_enc2_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[7:6]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_3_io_out_e)
  );
  LZC_enc2 LZC_enc2_4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[9:8]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_4_io_out_e)
  );
  LZC_enc2 LZC_enc2_5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[11:10]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_5_io_out_e)
  );
  LZC_enc2 LZC_enc2_6 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[13:12]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_6_io_out_e)
  );
  LZC_enc2 LZC_enc2_7 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[15:14]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_7_io_out_e)
  );
  LZC_enc2 LZC_enc2_8 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[17:16]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_8_io_out_e)
  );
  LZC_enc2 LZC_enc2_9 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[19:18]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_9_io_out_e)
  );
  LZC_enc2 LZC_enc2_10 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[21:20]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_10_io_out_e)
  );
  LZC_enc2 LZC_enc2_11 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[23:22]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_11_io_out_e)
  );
  LZC_enc2 LZC_enc2_12 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[25:24]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_12_io_out_e)
  );
  LZC_enc2 LZC_enc2_13 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[27:26]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_13_io_out_e)
  );
  LZC_enc2 LZC_enc2_14 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[29:28]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_14_io_out_e)
  );
  LZC_enc2 LZC_enc2_15 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[31:30]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_15_io_out_e)
  );
  LZC_Merge2 LZC_Merge2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_15_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_14_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_13_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_12_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_1_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_11_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_10_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_9_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_8_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_3_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_7_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_6_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_4_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_5_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_4_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_5_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_6 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_3_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_2_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_6_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_7 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_1_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_7_io_out_m)
  );
  LZC_Merge3 LZC_Merge3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_1_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_4_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_5_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_2_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_6_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_7_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_3_io_out_m)
  );
  LZC_Merge4 LZC_Merge4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge3_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge4_io_out_m)
  );
  LZC_Merge4 LZC_Merge4_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge3_2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge3_3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge4_1_io_out_m)
  );
  LZC_Merge5 LZC_Merge5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge4_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge4_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (io_out_c)
  );
endmodule

module FP_add_32_1(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
                reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
                io_in_en,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
                io_in_valid,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
  input  [31:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
  output [31:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
  output        io_out_valid	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
);

  wire [5:0]  _LZC32_2_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:412:26
  wire [23:0] _full_adder_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:394:28
  wire        _full_adder_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:394:28
  wire [7:0]  _exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:367:32
  wire        _exp_subtractor_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:367:32
  wire [7:0]  exp_wire_0 =
    {1'h0, io_in_a[30:23]} > 9'hFE
      ? 8'hFE
      : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:{14,33,61,68}, :338:19, :339:{36,42}, :340:19, :342:19, :370:28, :427:137, :428:98
  wire [7:0]  exp_wire_1 =
    {1'h0, io_in_b[30:23]} > 9'hFE
      ? 8'hFE
      : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:61, :339:36, :344:{14,33,68}, :345:19, :346:{36,42}, :347:19, :349:19, :370:28, :427:137, :428:98
  wire        eqexp_arrange = exp_wire_0 == exp_wire_1 & io_in_b[22:0] > io_in_a[22:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:68, :338:19, :339:42, :344:68, :345:19, :346:42, :354:25, :355:25, :378:{42,54,88}
  wire        _GEN = _exp_subtractor_io_out_c | eqexp_arrange;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:367:32, :378:42, :387:41
  wire [23:0] fracadd_in_b =
    _exp_subtractor_io_out_c
      ? {1'h1, io_in_a[22:0]} >> ~_exp_subtractor_io_out_s + 8'h1
      : {1'h1, eqexp_arrange ? io_in_a[22:0] : io_in_b[22:0]} >> _exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:339:36, :354:25, :355:25, :359:31, :367:32, :378:42, :386:67, :388:{41,85,115,155}, :427:137
  wire        diff_sign = io_in_a[31] ^ io_in_b[31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:332:25, :333:25, :391:48
  reg  [85:0] norm_out_frac_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:433:39
  reg  [7:0]  norm_out_exp;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:438:37
  reg         norm_out_sign;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:442:38
  reg         io_out_valid_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:444:34
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
    if (io_in_en) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:295:16
      automatic logic [7:0]  ref_exp = _exp_subtractor_io_out_c ? exp_wire_1 : exp_wire_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:68, :338:19, :339:42, :344:68, :345:19, :346:42, :367:32, :389:36
      automatic logic [8:0]  _GEN_0 = {1'h0, ref_exp};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:370:28, :389:36, :421:25
      automatic logic [8:0]  red = _GEN_0 - {3'h0, _LZC32_2_io_out_c};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:386:116, :412:26, :421:25
      automatic logic [8:0]  inc = _GEN_0 + 9'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:386:92, :421:25, :422:25
      automatic logic [85:0] _GEN_1 = {63'h0, _full_adder_io_out_s[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:394:28, :424:{38,56}
      automatic logic        _innermux_exp_true_T_2 = red == 9'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:421:25, :427:137
      automatic logic        _innermux_exp_false_T_2 = inc > 9'hFE;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:61, :422:25, :428:98
      norm_out_frac_r <=
        diff_sign
          ? (_full_adder_io_out_s[23]
               ? _GEN_1
               : red[8] | _innermux_exp_true_T_2 ? 86'h0 : _GEN_1 << _LZC32_2_io_out_c)
          : {63'h0,
             _full_adder_io_out_c
               ? (inc[8] | _innermux_exp_false_T_2
                    ? 23'h7FFFFF
                    : _full_adder_io_out_s[23:1])
               : _full_adder_io_out_s[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:391:48, :394:28, :412:26, :421:25, :422:25, :424:{38,56}, :427:{47,62,114,118,129,137}, :428:{48,75,79,90,98,134}, :433:{39,43}
      norm_out_exp <=
        diff_sign
          ? (_full_adder_io_out_s[23]
               ? ref_exp
               : red[8] | _innermux_exp_true_T_2 ? 8'h1 : red[7:0])
          : _full_adder_io_out_c
              ? (inc[8] | _innermux_exp_false_T_2 ? 8'hFE : inc[7:0])
              : ref_exp;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:389:36, :391:48, :394:28, :421:25, :422:25, :427:{62,118,137}, :428:{79,98}, :429:{46,94,109,141}, :430:{47,74,89,121}, :438:{37,41}
      norm_out_sign <=
        diff_sign
        & (_exp_subtractor_io_out_c
             ? ~_exp_subtractor_io_out_s + 8'h1
             : _exp_subtractor_io_out_s) < 8'h18 & ~_full_adder_io_out_c
        ^ (_GEN ? io_in_b[31] : io_in_a[31]);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:332:25, :333:25, :367:32, :386:{41,67,92,116}, :387:41, :390:37, :391:48, :394:28, :406:{37,80}, :427:137, :442:38
      io_out_valid_r <= io_in_valid;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:444:34
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
      automatic logic [31:0] _RANDOM[0:2];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
        end	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
        norm_out_frac_r = {_RANDOM[2'h0], _RANDOM[2'h1], _RANDOM[2'h2][21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :433:39
        norm_out_exp = _RANDOM[2'h2][29:22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :433:39, :438:37
        norm_out_sign = _RANDOM[2'h2][30];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :433:39, :442:38
        io_out_valid_r = _RANDOM[2'h2][31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :433:39, :444:34
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_subtractor exp_subtractor (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:367:32
    .io_in_a  (exp_wire_0),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:337:68, :338:19, :339:42
    .io_in_b  (exp_wire_1),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:344:68, :345:19, :346:42
    .io_out_s (_exp_subtractor_io_out_s),
    .io_out_c (_exp_subtractor_io_out_c)
  );
  full_adder full_adder (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:394:28
    .io_in_a  ({1'h1, _GEN ? io_in_b[22:0] : io_in_a[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:339:36, :354:25, :355:25, :387:41
    .io_in_b  (diff_sign ? ~fracadd_in_b + 24'h1 : fracadd_in_b),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:388:41, :391:48, :396:{27,47,69}
    .io_out_s (_full_adder_io_out_s),
    .io_out_c (_full_adder_io_out_c)
  );
  LZC32_2 LZC32_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:412:26
    .io_in_d  ({_full_adder_io_out_s, 8'hFF}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:394:28, :413:{35,82}
    .io_out_c (_LZC32_2_io_out_c)
  );
  assign io_out_s = {norm_out_sign, norm_out_exp, norm_out_frac_r[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :433:39, :436:30, :438:37, :442:38, :445:47
  assign io_out_valid = io_out_valid_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:292:9, :444:34
endmodule

