// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module full_subtractor(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9
  input  [7:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
               io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output [7:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output       io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
);

  wire [8:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:100:23
  assign io_out_s = result[7:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :101:23
  assign io_out_c = result[8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :102:23
endmodule

module divider_BW25(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
                reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
                io_in_ready,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
                io_in_valid,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
  input  [24:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
  output [24:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
  output        io_out_valid	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
);

  reg [49:0] a_aux_reg_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] a_aux_reg_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28
  reg [49:0] b_aux_reg_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [49:0] b_aux_reg_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28
  reg [24:0] result_reg_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg [24:0] result_reg_14;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29
  reg        sr_out_valid_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  reg        sr_out_valid_14;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
    if (reset) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      a_aux_reg_0 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_1 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_2 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_3 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_4 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_5 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_6 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_7 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_8 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_9 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_10 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_11 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_12 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      a_aux_reg_13 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:{28,44}
      b_aux_reg_0 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_1 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_2 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_3 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_4 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_5 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_6 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_7 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_8 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_9 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_10 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_11 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_12 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      b_aux_reg_13 <= 50'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:44, :131:28
      result_reg_0 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_1 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_2 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_3 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_4 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_5 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_6 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_7 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_8 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_9 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_10 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_11 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_12 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_13 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      result_reg_14 <= 25'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:{29,45}
      sr_out_valid_0 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_1 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_2 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_3 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_4 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_5 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_6 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_7 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_8 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_9 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_10 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_11 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_12 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_13 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
      sr_out_valid_14 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :136:31
    end
    else if (io_in_ready) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16
      automatic logic        t_24 = io_in_a >= io_in_b;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:155:22
      automatic logic [49:0] _GEN;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_1_23;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_2_22;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_3_21;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_4_20;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_5_19;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_6_18;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_7_17;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_8_16;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_9_15;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_10_14;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_11_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_12_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic [49:0] _GEN_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      automatic logic        t_13_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:168:35
      _GEN = {1'h0, b_aux_reg_0[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_1_23 = a_aux_reg_0 >= _GEN;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_0 = {1'h0, b_aux_reg_1[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_2_22 = a_aux_reg_1 >= _GEN_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_1 = {1'h0, b_aux_reg_2[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_3_21 = a_aux_reg_2 >= _GEN_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_2 = {1'h0, b_aux_reg_3[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_4_20 = a_aux_reg_3 >= _GEN_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_3 = {1'h0, b_aux_reg_4[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_5_19 = a_aux_reg_4 >= _GEN_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_4 = {1'h0, b_aux_reg_5[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_6_18 = a_aux_reg_5 >= _GEN_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_5 = {1'h0, b_aux_reg_6[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_7_17 = a_aux_reg_6 >= _GEN_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_6 = {1'h0, b_aux_reg_7[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_8_16 = a_aux_reg_7 >= _GEN_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_7 = {1'h0, b_aux_reg_8[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_9_15 = a_aux_reg_8 >= _GEN_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_8 = {1'h0, b_aux_reg_9[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_10_14 = a_aux_reg_9 >= _GEN_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_9 = {1'h0, b_aux_reg_10[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_11_13 = a_aux_reg_10 >= _GEN_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_10 = {1'h0, b_aux_reg_11[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_12_12 = a_aux_reg_11 >= _GEN_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      _GEN_11 = {1'h0, b_aux_reg_12[49:1]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :131:28, :166:47, :168:35
      t_13_11 = a_aux_reg_12 >= _GEN_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:35
      a_aux_reg_0 <= t_24 ? {io_in_a, 25'h0} - {io_in_b, 25'h0} : {io_in_a, 25'h0};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :135:45, :141:33, :155:{22,36}, :156:{28,35}, :159:28
      a_aux_reg_1 <= t_1_23 ? a_aux_reg_0 - _GEN : a_aux_reg_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_2 <= t_2_22 ? a_aux_reg_1 - _GEN_0 : a_aux_reg_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_3 <= t_3_21 ? a_aux_reg_2 - _GEN_1 : a_aux_reg_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_4 <= t_4_20 ? a_aux_reg_3 - _GEN_2 : a_aux_reg_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_5 <= t_5_19 ? a_aux_reg_4 - _GEN_3 : a_aux_reg_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_6 <= t_6_18 ? a_aux_reg_5 - _GEN_4 : a_aux_reg_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_7 <= t_7_17 ? a_aux_reg_6 - _GEN_5 : a_aux_reg_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_8 <= t_8_16 ? a_aux_reg_7 - _GEN_6 : a_aux_reg_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_9 <= t_9_15 ? a_aux_reg_8 - _GEN_7 : a_aux_reg_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_10 <= t_10_14 ? a_aux_reg_9 - _GEN_8 : a_aux_reg_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_11 <= t_11_13 ? a_aux_reg_10 - _GEN_9 : a_aux_reg_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_12 <= t_12_12 ? a_aux_reg_11 - _GEN_10 : a_aux_reg_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      a_aux_reg_13 <= t_13_11 ? a_aux_reg_12 - _GEN_11 : a_aux_reg_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:130:28, :168:{35,49}, :169:{28,48}, :172:28
      b_aux_reg_0 <= {io_in_b, 25'h0};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :135:45, :142:33
      b_aux_reg_1 <= _GEN;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_2 <= _GEN_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_3 <= _GEN_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_4 <= _GEN_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_5 <= _GEN_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_6 <= _GEN_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_7 <= _GEN_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_8 <= _GEN_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_9 <= _GEN_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_10 <= _GEN_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_11 <= _GEN_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_12 <= _GEN_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      b_aux_reg_13 <= _GEN_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:131:28, :168:35
      result_reg_0 <= {t_24, 24'h0};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :155:22, :162:32
      result_reg_1 <= {result_reg_0[24], t_1_23, result_reg_0[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :167:45, :168:35, :175:32
      result_reg_2 <= {result_reg_1[24:23], t_2_22, result_reg_1[21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_3 <= {result_reg_2[24:22], t_3_21, result_reg_2[20:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_4 <= {result_reg_3[24:21], t_4_20, result_reg_3[19:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_5 <= {result_reg_4[24:20], t_5_19, result_reg_4[18:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_6 <= {result_reg_5[24:19], t_6_18, result_reg_5[17:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_7 <= {result_reg_6[24:18], t_7_17, result_reg_6[16:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_8 <= {result_reg_7[24:17], t_8_16, result_reg_7[15:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_9 <= {result_reg_8[24:16], t_9_15, result_reg_8[14:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_10 <= {result_reg_9[24:15], t_10_14, result_reg_9[13:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_11 <= {result_reg_10[24:14], t_11_13, result_reg_10[12:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_12 <= {result_reg_11[24:13], t_12_12, result_reg_11[11:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_13 <= {result_reg_12[24:12], t_13_11, result_reg_12[10:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:135:29, :168:35, :175:32
      result_reg_14 <=
        {result_reg_13[24:11],
         a_aux_reg_13 >= {1'h0, b_aux_reg_13[49:1]},
         result_reg_13[9:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:118:16, :130:28, :131:28, :135:29, :166:47, :168:35, :175:32
      sr_out_valid_0 <= io_in_valid;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_1 <= sr_out_valid_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_2 <= sr_out_valid_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_3 <= sr_out_valid_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_4 <= sr_out_valid_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_5 <= sr_out_valid_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_6 <= sr_out_valid_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_7 <= sr_out_valid_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_8 <= sr_out_valid_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_9 <= sr_out_valid_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_10 <= sr_out_valid_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_11 <= sr_out_valid_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_12 <= sr_out_valid_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_13 <= sr_out_valid_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
      sr_out_valid_14 <= sr_out_valid_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:136:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      automatic logic [31:0] _RANDOM[0:59];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
        for (logic [5:0] i = 6'h0; i < 6'h3C; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
        end	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
        a_aux_reg_0 = {_RANDOM[6'h0], _RANDOM[6'h1][17:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_1 = {_RANDOM[6'h1][31:18], _RANDOM[6'h2], _RANDOM[6'h3][3:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_2 = {_RANDOM[6'h3][31:4], _RANDOM[6'h4][21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_3 = {_RANDOM[6'h4][31:22], _RANDOM[6'h5], _RANDOM[6'h6][7:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_4 = {_RANDOM[6'h6][31:8], _RANDOM[6'h7][25:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_5 = {_RANDOM[6'h7][31:26], _RANDOM[6'h8], _RANDOM[6'h9][11:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_6 = {_RANDOM[6'h9][31:12], _RANDOM[6'hA][29:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_7 = {_RANDOM[6'hA][31:30], _RANDOM[6'hB], _RANDOM[6'hC][15:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_8 = {_RANDOM[6'hC][31:16], _RANDOM[6'hD], _RANDOM[6'hE][1:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_9 = {_RANDOM[6'hE][31:2], _RANDOM[6'hF][19:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_10 = {_RANDOM[6'hF][31:20], _RANDOM[6'h10], _RANDOM[6'h11][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_11 = {_RANDOM[6'h11][31:6], _RANDOM[6'h12][23:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_12 = {_RANDOM[6'h12][31:24], _RANDOM[6'h13], _RANDOM[6'h14][9:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        a_aux_reg_13 = {_RANDOM[6'h14][31:10], _RANDOM[6'h15][27:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :130:28
        b_aux_reg_0 = {_RANDOM[6'h17][31:14], _RANDOM[6'h18]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_1 = {_RANDOM[6'h19], _RANDOM[6'h1A][17:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_2 = {_RANDOM[6'h1A][31:18], _RANDOM[6'h1B], _RANDOM[6'h1C][3:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_3 = {_RANDOM[6'h1C][31:4], _RANDOM[6'h1D][21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_4 = {_RANDOM[6'h1D][31:22], _RANDOM[6'h1E], _RANDOM[6'h1F][7:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_5 = {_RANDOM[6'h1F][31:8], _RANDOM[6'h20][25:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_6 = {_RANDOM[6'h20][31:26], _RANDOM[6'h21], _RANDOM[6'h22][11:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_7 = {_RANDOM[6'h22][31:12], _RANDOM[6'h23][29:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_8 = {_RANDOM[6'h23][31:30], _RANDOM[6'h24], _RANDOM[6'h25][15:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_9 = {_RANDOM[6'h25][31:16], _RANDOM[6'h26], _RANDOM[6'h27][1:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_10 = {_RANDOM[6'h27][31:2], _RANDOM[6'h28][19:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_11 = {_RANDOM[6'h28][31:20], _RANDOM[6'h29], _RANDOM[6'h2A][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_12 = {_RANDOM[6'h2A][31:6], _RANDOM[6'h2B][23:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        b_aux_reg_13 = {_RANDOM[6'h2B][31:24], _RANDOM[6'h2C], _RANDOM[6'h2D][9:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :131:28
        result_reg_0 = {_RANDOM[6'h2E][31:28], _RANDOM[6'h2F][20:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_1 = {_RANDOM[6'h2F][31:21], _RANDOM[6'h30][13:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_2 = {_RANDOM[6'h30][31:14], _RANDOM[6'h31][6:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_3 = _RANDOM[6'h31][31:7];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_4 = _RANDOM[6'h32][24:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_5 = {_RANDOM[6'h32][31:25], _RANDOM[6'h33][17:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_6 = {_RANDOM[6'h33][31:18], _RANDOM[6'h34][10:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_7 = {_RANDOM[6'h34][31:11], _RANDOM[6'h35][3:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_8 = _RANDOM[6'h35][28:4];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_9 = {_RANDOM[6'h35][31:29], _RANDOM[6'h36][21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_10 = {_RANDOM[6'h36][31:22], _RANDOM[6'h37][14:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_11 = {_RANDOM[6'h37][31:15], _RANDOM[6'h38][7:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_12 = {_RANDOM[6'h38][31:8], _RANDOM[6'h39][0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_13 = _RANDOM[6'h39][25:1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        result_reg_14 = {_RANDOM[6'h39][31:26], _RANDOM[6'h3A][18:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
        sr_out_valid_0 = _RANDOM[6'h3A][19];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_1 = _RANDOM[6'h3A][20];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_2 = _RANDOM[6'h3A][21];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_3 = _RANDOM[6'h3A][22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_4 = _RANDOM[6'h3A][23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_5 = _RANDOM[6'h3A][24];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_6 = _RANDOM[6'h3A][25];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_7 = _RANDOM[6'h3A][26];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_8 = _RANDOM[6'h3A][27];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_9 = _RANDOM[6'h3A][28];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_10 = _RANDOM[6'h3A][29];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_11 = _RANDOM[6'h3A][30];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_12 = _RANDOM[6'h3A][31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29, :136:31
        sr_out_valid_13 = _RANDOM[6'h3B][0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :136:31
        sr_out_valid_14 = _RANDOM[6'h3B][1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :136:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_s = result_reg_14;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :135:29
  assign io_out_valid = sr_out_valid_14;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:116:9, :136:31
endmodule

module FP_divider_32_15(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
                reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
                io_in_en,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
                io_in_valid,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
  input  [31:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
  output [31:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
  output        io_out_valid	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
);

  wire [24:0] _divider_BW25_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:80:30
  wire [7:0]  _postProcess_exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:75:44
  wire        _postProcess_exp_subtractor_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:75:44
  wire [7:0]  exp_wire_1 =
    (&(io_in_b[30:23])) ? 8'hFE : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:46:36, :48:39, :53:{17,36,47}, :54:19, :55:{39,49}, :56:19, :58:19, :95:60
  reg         uo_check_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         uo_check;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
  reg         carry_flag_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg         carry_flag;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
  reg  [7:0]  exp_sum_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg  [7:0]  exp_sum;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
  reg         new_sign_reg_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  reg         new_sign_reg;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
  wire [8:0]  _GEN = {1'h0, exp_sum};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:78:40, :90:32, :95:60
  wire [8:0]  _GEN_0 = {8'h0, ~(_divider_BW25_io_out_s[24])};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:80:30, :89:39, :95:{60,64}
  wire        o_flag_reg = uo_check & (~carry_flag | _GEN - _GEN_0 > 9'hFE);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33, :88:35, :95:{25,35,47,60,84}
  wire        u_flag_reg = ~uo_check & (carry_flag | _GEN - _GEN_0 == 9'h0);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33, :88:35, :95:60, :96:{25,26,47,60,84}
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
    if (io_in_en) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:19:16
      uo_check_r <= exp_wire_1 < 8'h7F;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:53:47, :54:19, :55:49, :77:55, :87:{33,46}
      uo_check_r_1 <= uo_check_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_2 <= uo_check_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_3 <= uo_check_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_4 <= uo_check_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_5 <= uo_check_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_6 <= uo_check_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_7 <= uo_check_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_8 <= uo_check_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_9 <= uo_check_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_10 <= uo_check_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_11 <= uo_check_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_12 <= uo_check_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check_r_13 <= uo_check_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      uo_check <= uo_check_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:87:33
      carry_flag_r <= _postProcess_exp_subtractor_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:75:44, :88:35
      carry_flag_r_1 <= carry_flag_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_2 <= carry_flag_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_3 <= carry_flag_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_4 <= carry_flag_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_5 <= carry_flag_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_6 <= carry_flag_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_7 <= carry_flag_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_8 <= carry_flag_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_9 <= carry_flag_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_10 <= carry_flag_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_11 <= carry_flag_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_12 <= carry_flag_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag_r_13 <= carry_flag_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      carry_flag <= carry_flag_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:88:35
      exp_sum_r <= _postProcess_exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:75:44, :90:32
      exp_sum_r_1 <= exp_sum_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_2 <= exp_sum_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_3 <= exp_sum_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_4 <= exp_sum_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_5 <= exp_sum_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_6 <= exp_sum_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_7 <= exp_sum_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_8 <= exp_sum_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_9 <= exp_sum_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_10 <= exp_sum_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_11 <= exp_sum_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_12 <= exp_sum_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum_r_13 <= exp_sum_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      exp_sum <= exp_sum_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:90:32
      new_sign_reg_r <= io_in_a[31] ^ io_in_b[31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:41:28, :42:28, :72:35, :92:37
      new_sign_reg_r_1 <= new_sign_reg_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_2 <= new_sign_reg_r_1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_3 <= new_sign_reg_r_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_4 <= new_sign_reg_r_3;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_5 <= new_sign_reg_r_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_6 <= new_sign_reg_r_5;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_7 <= new_sign_reg_r_6;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_8 <= new_sign_reg_r_7;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_9 <= new_sign_reg_r_8;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_10 <= new_sign_reg_r_9;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_11 <= new_sign_reg_r_10;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_12 <= new_sign_reg_r_11;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg_r_13 <= new_sign_reg_r_12;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
      new_sign_reg <= new_sign_reg_r_13;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:92:37
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
      automatic logic [31:0] _RANDOM[0:5];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
        for (logic [2:0] i = 3'h0; i < 3'h6; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
        end	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
        uo_check_r = _RANDOM[3'h0][0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_1 = _RANDOM[3'h0][1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_2 = _RANDOM[3'h0][2];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_3 = _RANDOM[3'h0][3];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_4 = _RANDOM[3'h0][4];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_5 = _RANDOM[3'h0][5];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_6 = _RANDOM[3'h0][6];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_7 = _RANDOM[3'h0][7];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_8 = _RANDOM[3'h0][8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_9 = _RANDOM[3'h0][9];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_10 = _RANDOM[3'h0][10];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_11 = _RANDOM[3'h0][11];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_12 = _RANDOM[3'h0][12];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check_r_13 = _RANDOM[3'h0][13];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        uo_check = _RANDOM[3'h0][14];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33
        carry_flag_r = _RANDOM[3'h0][15];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_1 = _RANDOM[3'h0][16];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_2 = _RANDOM[3'h0][17];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_3 = _RANDOM[3'h0][18];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_4 = _RANDOM[3'h0][19];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_5 = _RANDOM[3'h0][20];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_6 = _RANDOM[3'h0][21];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_7 = _RANDOM[3'h0][22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_8 = _RANDOM[3'h0][23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_9 = _RANDOM[3'h0][24];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_10 = _RANDOM[3'h0][25];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_11 = _RANDOM[3'h0][26];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_12 = _RANDOM[3'h0][27];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag_r_13 = _RANDOM[3'h0][28];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        carry_flag = _RANDOM[3'h0][29];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :88:35
        exp_sum_r = {_RANDOM[3'h0][31:30], _RANDOM[3'h1][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :87:33, :90:32
        exp_sum_r_1 = _RANDOM[3'h1][13:6];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_2 = _RANDOM[3'h1][21:14];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_3 = _RANDOM[3'h1][29:22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_4 = {_RANDOM[3'h1][31:30], _RANDOM[3'h2][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_5 = _RANDOM[3'h2][13:6];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_6 = _RANDOM[3'h2][21:14];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_7 = _RANDOM[3'h2][29:22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_8 = {_RANDOM[3'h2][31:30], _RANDOM[3'h3][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_9 = _RANDOM[3'h3][13:6];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_10 = _RANDOM[3'h3][21:14];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_11 = _RANDOM[3'h3][29:22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_12 = {_RANDOM[3'h3][31:30], _RANDOM[3'h4][5:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum_r_13 = _RANDOM[3'h4][13:6];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        exp_sum = _RANDOM[3'h4][21:14];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32
        new_sign_reg_r = _RANDOM[3'h4][22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_1 = _RANDOM[3'h4][23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_2 = _RANDOM[3'h4][24];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_3 = _RANDOM[3'h4][25];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_4 = _RANDOM[3'h4][26];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_5 = _RANDOM[3'h4][27];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_6 = _RANDOM[3'h4][28];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_7 = _RANDOM[3'h4][29];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_8 = _RANDOM[3'h4][30];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_9 = _RANDOM[3'h4][31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :90:32, :92:37
        new_sign_reg_r_10 = _RANDOM[3'h5][0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :92:37
        new_sign_reg_r_11 = _RANDOM[3'h5][1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :92:37
        new_sign_reg_r_12 = _RANDOM[3'h5][2];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :92:37
        new_sign_reg_r_13 = _RANDOM[3'h5][3];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :92:37
        new_sign_reg = _RANDOM[3'h5][4];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :92:37
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_subtractor postProcess_exp_subtractor (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:75:44
    .io_in_a
      ((&(io_in_a[30:23])) ? 8'hFE : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:46:{17,36,47}, :47:19, :48:{39,49}, :49:19, :51:19, :95:60
    .io_in_b  (exp_wire_1 - 8'h7F),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:53:47, :54:19, :55:49, :77:55
    .io_out_s (_postProcess_exp_subtractor_io_out_s),
    .io_out_c (_postProcess_exp_subtractor_io_out_c)
  );
  divider_BW25 divider_BW25 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:80:30
    .clock        (clock),
    .reset        (reset),
    .io_in_ready  (io_in_en),
    .io_in_valid  (io_in_valid),
    .io_in_a      ({1'h1, io_in_a[22:0], 1'h0}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:63:28, :68:31, :78:40, :84:45
    .io_in_b      ({1'h1, io_in_b[22:0], 1'h0}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:64:28, :68:31, :78:40, :85:45
    .io_out_s     (_divider_BW25_io_out_s),
    .io_out_valid (io_out_valid)
  );
  assign io_out_s =
    {new_sign_reg,
     o_flag_reg
       ? 8'hFE
       : u_flag_reg ? 8'h1 : _divider_BW25_io_out_s[24] ? exp_sum : exp_sum - 8'h1,
     o_flag_reg
       ? 23'h7FFFFF
       : u_flag_reg
           ? 23'h0
           : _divider_BW25_io_out_s[24]
               ? _divider_BW25_io_out_s[23:1]
               : _divider_BW25_io_out_s[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:17:9, :46:36, :48:39, :80:30, :89:39, :90:32, :92:37, :95:25, :96:25, :102:{22,47,72,109}, :103:{23,49,74,98,125}, :104:37
endmodule

