// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module full_adder(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9
  input  [7:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
               io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output [7:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output       io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
);

  wire [8:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:86:23
  assign io_out_s = result[7:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :87:23
  assign io_out_c = result[8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :88:23
endmodule

module multiplier(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:105:9
  input  [23:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
  output [47:0] io_out_s	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
);

  assign io_out_s = {24'h0, io_in_a} * {24'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:105:9, :112:23
endmodule

module FP_mult_32_1_v2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
                reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
                io_in_en,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
                io_in_valid,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
  input  [31:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
  output [31:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
  output        io_out_valid	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
);

  wire [47:0] _multiplier_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:242:33
  wire [7:0]  _exp_adder_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:231:27
  wire        _exp_adder_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:231:27
  wire [7:0]  exp_wire_1 =
    (&(io_in_b[30:23])) ? 8'hFE : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:195:33, :197:36, :202:{14,33,44}, :203:19, :204:{36,46}, :205:19, :207:19, :262:74
  reg  [31:0] io_out_s_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:287:30
  reg         io_out_valid_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:34
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
    if (io_in_en) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:156:16
      automatic logic       uo_check = exp_wire_1 < 8'h7F;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:202:44, :203:19, :204:46, :233:38, :253:69
      automatic logic [8:0] _o_flag_reg_T_1 =
        {1'h0, _exp_adder_io_out_s} + {8'h0, _multiplier_io_out_s[47]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :231:27, :242:33, :257:51, :262:74
      automatic logic       u_flag_reg =
        uo_check & (~_exp_adder_io_out_c | _o_flag_reg_T_1 == 9'h0);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:231:27, :253:69, :262:{39,49,61,74,95}
      automatic logic       o_flag_reg =
        ~uo_check & (_exp_adder_io_out_c | _o_flag_reg_T_1 > 9'hFE);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:231:27, :253:69, :262:74, :263:{39,40,61,95}
      io_out_s_r <=
        {io_in_a[31] ^ io_in_b[31],
         u_flag_reg
           ? 8'h1
           : o_flag_reg
               ? 8'hFE
               : _multiplier_io_out_s[47]
                   ? _exp_adder_io_out_s + 8'h1
                   : _exp_adder_io_out_s,
         u_flag_reg
           ? 23'h0
           : o_flag_reg
               ? 23'h7FFFFF
               : _multiplier_io_out_s[47]
                   ? _multiplier_io_out_s[46:24]
                   : _multiplier_io_out_s[45:23]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:184:25, :185:25, :195:33, :197:36, :225:33, :231:27, :242:33, :257:51, :262:39, :263:39, :271:{45,105}, :272:{46,108,162}, :279:47, :280:48, :285:22, :286:23, :287:{30,51}
      io_out_valid_r <= io_in_valid;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:34
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
      automatic logic [31:0] _RANDOM[0:1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
        end	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
        io_out_s_r = _RANDOM[1'h0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :287:30
        io_out_valid_r = _RANDOM[1'h1][0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :288:34
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_adder exp_adder (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:231:27
    .io_in_a
      ((&(io_in_a[30:23])) ? 8'hFE : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:195:{14,33,44}, :196:19, :197:{36,46}, :198:19, :200:19, :262:74
    .io_in_b  (exp_wire_1 - 8'h7F),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:202:44, :203:19, :204:46, :233:38
    .io_out_s (_exp_adder_io_out_s),
    .io_out_c (_exp_adder_io_out_c)
  );
  multiplier multiplier (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:242:33
    .io_in_a  ({1'h1, io_in_a[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :212:25, :217:31
    .io_in_b  ({1'h1, io_in_b[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :213:25, :218:31
    .io_out_s (_multiplier_io_out_s)
  );
  assign io_out_s = io_out_s_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :287:30
  assign io_out_valid = io_out_valid_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:153:9, :288:34
endmodule

