// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module full_adder(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9
  input  [7:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
               io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output [7:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output       io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
);

  wire [8:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:86:23
  assign io_out_s = result[7:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :87:23
  assign io_out_c = result[8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :88:23
endmodule

module multiplier(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:105:9
  input  [23:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
  output [47:0] io_out_s	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:106:16
);

  assign io_out_s = {24'h0, io_in_a} * {24'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:105:9, :112:23
endmodule

module FP_mult_32_1_v2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
  input  [31:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:152:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:152:16
  output [31:0] io_out_s	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:152:16
);

  wire [47:0] _multiplier_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:238:33
  wire [7:0]  _exp_adder_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:227:27
  wire        _exp_adder_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:227:27
  wire [7:0]  exp_wire_1 =
    (&(io_in_b[30:23])) ? 8'hFE : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:191:33, :193:36, :198:{14,33,44}, :199:19, :200:{36,46}, :201:19, :203:19, :258:74
  reg  [31:0] io_out_s_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:283:30
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
    automatic logic       uo_check = exp_wire_1 < 8'h7F;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:198:44, :199:19, :200:46, :229:38, :249:69
    automatic logic [8:0] _o_flag_reg_T_1 =
      {1'h0, _exp_adder_io_out_s} + {8'h0, _multiplier_io_out_s[47]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9, :227:27, :238:33, :253:51, :258:74
    automatic logic       u_flag_reg =
      uo_check & (~_exp_adder_io_out_c | _o_flag_reg_T_1 == 9'h0);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:227:27, :249:69, :258:{39,49,61,74,95}
    automatic logic       o_flag_reg =
      ~uo_check & (_exp_adder_io_out_c | _o_flag_reg_T_1 > 9'hFE);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:227:27, :249:69, :258:74, :259:{39,40,61,95}
    io_out_s_r <=
      {io_in_a[31] ^ io_in_b[31],
       u_flag_reg
         ? 8'h1
         : o_flag_reg
             ? 8'hFE
             : _multiplier_io_out_s[47]
                 ? _exp_adder_io_out_s + 8'h1
                 : _exp_adder_io_out_s,
       u_flag_reg
         ? 23'h0
         : o_flag_reg
             ? 23'h7FFFFF
             : _multiplier_io_out_s[47]
                 ? _multiplier_io_out_s[46:24]
                 : _multiplier_io_out_s[45:23]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:180:25, :181:25, :191:33, :193:36, :221:33, :227:27, :238:33, :253:51, :258:39, :259:39, :267:{45,105}, :268:{46,108,162}, :275:47, :276:48, :281:22, :282:23, :283:{30,51}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
      automatic logic [31:0] _RANDOM[0:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
        io_out_s_r = _RANDOM[/*Zero width*/ 1'b0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9, :283:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_adder exp_adder (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:227:27
    .io_in_a
      ((&(io_in_a[30:23])) ? 8'hFE : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:191:{14,33,44}, :192:19, :193:{36,46}, :194:19, :196:19, :258:74
    .io_in_b  (exp_wire_1 - 8'h7F),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:198:44, :199:19, :200:46, :229:38
    .io_out_s (_exp_adder_io_out_s),
    .io_out_c (_exp_adder_io_out_c)
  );
  multiplier multiplier (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:238:33
    .io_in_a  ({1'h1, io_in_a[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9, :208:25, :213:31
    .io_in_b  ({1'h1, io_in_b[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9, :209:25, :214:31
    .io_out_s (_multiplier_io_out_s)
  );
  assign io_out_s = io_out_s_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:149:9, :283:30
endmodule

module full_subtractor(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9
  input  [7:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
               io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output [7:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
  output       io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:92:16
);

  wire [8:0] result = {1'h0, io_in_a} - {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:100:23
  assign io_out_s = result[7:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :101:23
  assign io_out_c = result[8];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:91:9, :100:23, :102:23
endmodule

module full_adder_4(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9
  input  [23:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output [23:0] io_out_s,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
  output        io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:78:16
);

  wire [24:0] result = {1'h0, io_in_a} + {1'h0, io_in_b};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:86:23
  assign io_out_s = result[23:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :87:23
  assign io_out_c = result[24];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:77:9, :86:23, :88:23
endmodule

module LZC_enc2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:7:9
  input  [1:0] io_in_r,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:8:16
  output [1:0] io_out_e	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:8:16
);

  assign io_out_e = io_in_r == 2'h0 ? 2'h2 : {1'h0, io_in_r == 2'h1};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:7:9, :23:48, src/main/scala/chisel3/util/Mux.scala:126:16
endmodule

module LZC_Merge2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [1:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [2:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[1] & io_in_l[1],
     io_in_h[1] ? ~(io_in_l[1]) : io_in_h[1],
     io_in_h[1] ? io_in_l[0] : io_in_h[0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge3(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [2:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [3:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[2] & io_in_l[2],
     io_in_h[2] ? ~(io_in_l[2]) : io_in_h[2],
     io_in_h[2] ? io_in_l[1:0] : io_in_h[1:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge4(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [3:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [4:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[3] & io_in_l[3],
     io_in_h[3] ? ~(io_in_l[3]) : io_in_h[3],
     io_in_h[3] ? io_in_l[2:0] : io_in_h[2:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC_Merge5(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9
  input  [4:0] io_in_h,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
               io_in_l,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
  output [5:0] io_out_m	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:63:16
);

  assign io_out_m =
    {io_in_h[4] & io_in_l[4],
     io_in_h[4] ? ~(io_in_l[4]) : io_in_h[4],
     io_in_h[4] ? io_in_l[3:0] : io_in_h[3:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:62:9, :71:{27,34,43}, :72:{23,46}, :73:{20,50,67}, :74:33
endmodule

module LZC32_2(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:29:9
  input  [31:0] io_in_d,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:30:16
  output [5:0]  io_out_c	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:30:16
);

  wire [4:0] _LZC_Merge4_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [4:0] _LZC_Merge4_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [3:0] _LZC_Merge3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_7_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_6_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_5_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_4_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_3_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_1_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [2:0] _LZC_Merge2_io_out_m;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
  wire [1:0] _LZC_enc2_15_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_14_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_13_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_12_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_11_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_10_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_9_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_8_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_7_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_6_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_5_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_4_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_3_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_2_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_1_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  wire [1:0] _LZC_enc2_io_out_e;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
  LZC_enc2 LZC_enc2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[1:0]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_io_out_e)
  );
  LZC_enc2 LZC_enc2_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[3:2]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_1_io_out_e)
  );
  LZC_enc2 LZC_enc2_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[5:4]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_2_io_out_e)
  );
  LZC_enc2 LZC_enc2_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[7:6]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_3_io_out_e)
  );
  LZC_enc2 LZC_enc2_4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[9:8]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_4_io_out_e)
  );
  LZC_enc2 LZC_enc2_5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[11:10]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_5_io_out_e)
  );
  LZC_enc2 LZC_enc2_6 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[13:12]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_6_io_out_e)
  );
  LZC_enc2 LZC_enc2_7 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[15:14]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_7_io_out_e)
  );
  LZC_enc2 LZC_enc2_8 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[17:16]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_8_io_out_e)
  );
  LZC_enc2 LZC_enc2_9 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[19:18]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_9_io_out_e)
  );
  LZC_enc2 LZC_enc2_10 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[21:20]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_10_io_out_e)
  );
  LZC_enc2 LZC_enc2_11 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[23:22]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_11_io_out_e)
  );
  LZC_enc2 LZC_enc2_12 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[25:24]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_12_io_out_e)
  );
  LZC_enc2 LZC_enc2_13 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[27:26]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_13_io_out_e)
  );
  LZC_enc2 LZC_enc2_14 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[29:28]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_14_io_out_e)
  );
  LZC_enc2 LZC_enc2_15 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_r  (io_in_d[31:30]),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:37:27
    .io_out_e (_LZC_enc2_15_io_out_e)
  );
  LZC_Merge2 LZC_Merge2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_15_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_14_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_13_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_12_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_1_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_11_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_10_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_2_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_9_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_8_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_3_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_7_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_6_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_4_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_5_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_4_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_5_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_6 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_3_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_2_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_6_io_out_m)
  );
  LZC_Merge2 LZC_Merge2_7 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_enc2_1_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_in_l  (_LZC_enc2_io_out_e),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:35:50
    .io_out_m (_LZC_Merge2_7_io_out_m)
  );
  LZC_Merge3 LZC_Merge3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_1_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_4_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_5_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_2_io_out_m)
  );
  LZC_Merge3 LZC_Merge3_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge2_6_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge2_7_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge3_3_io_out_m)
  );
  LZC_Merge4 LZC_Merge4 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge3_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge4_io_out_m)
  );
  LZC_Merge4 LZC_Merge4_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge3_2_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge3_3_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (_LZC_Merge4_1_io_out_m)
  );
  LZC_Merge5 LZC_Merge5 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_h  (_LZC_Merge4_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_in_l  (_LZC_Merge4_1_io_out_m),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\Binary_Modules\\BinaryDesigns.scala:45:37
    .io_out_m (io_out_c)
  );
endmodule

module FP_add_32_1(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
  input  [31:0] io_in_a,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:291:16
                io_in_b,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:291:16
  output [31:0] io_out_s	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:291:16
);

  wire [5:0]  _LZC32_2_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:408:26
  wire [23:0] _full_adder_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:390:28
  wire        _full_adder_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:390:28
  wire [7:0]  _exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:363:32
  wire        _exp_subtractor_io_out_c;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:363:32
  wire [7:0]  exp_wire_0 =
    {1'h0, io_in_a[30:23]} > 9'hFE
      ? 8'hFE
      : io_in_a[30:23] == 8'h0 ? 8'h1 : io_in_a[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:{14,33,61,68}, :334:19, :335:{36,42}, :336:19, :338:19, :366:28, :423:137, :424:98
  wire [7:0]  exp_wire_1 =
    {1'h0, io_in_b[30:23]} > 9'hFE
      ? 8'hFE
      : io_in_b[30:23] == 8'h0 ? 8'h1 : io_in_b[30:23];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:61, :335:36, :340:{14,33,68}, :341:19, :342:{36,42}, :343:19, :345:19, :366:28, :423:137, :424:98
  wire        eqexp_arrange = exp_wire_0 == exp_wire_1 & io_in_b[22:0] > io_in_a[22:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:68, :334:19, :335:42, :340:68, :341:19, :342:42, :350:25, :351:25, :374:{42,54,88}
  wire        _GEN = _exp_subtractor_io_out_c | eqexp_arrange;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:363:32, :374:42, :383:41
  wire [23:0] fracadd_in_b =
    _exp_subtractor_io_out_c
      ? {1'h1, io_in_a[22:0]} >> ~_exp_subtractor_io_out_s + 8'h1
      : {1'h1, eqexp_arrange ? io_in_a[22:0] : io_in_b[22:0]} >> _exp_subtractor_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:291:16, :350:25, :351:25, :355:31, :363:32, :374:42, :382:67, :384:{41,85,115,155}, :423:137, :440:34
  wire        diff_sign = io_in_a[31] ^ io_in_b[31];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:328:25, :329:25, :387:48
  reg  [85:0] norm_out_frac_r;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:429:39
  reg  [7:0]  norm_out_exp;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:434:37
  reg         norm_out_sign;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:438:38
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
    automatic logic [7:0]  ref_exp = _exp_subtractor_io_out_c ? exp_wire_1 : exp_wire_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:68, :334:19, :335:42, :340:68, :341:19, :342:42, :363:32, :385:36
    automatic logic [8:0]  _GEN_0 = {1'h0, ref_exp};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:366:28, :385:36, :417:25
    automatic logic [8:0]  red = _GEN_0 - {3'h0, _LZC32_2_io_out_c};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:382:116, :408:26, :417:25
    automatic logic [8:0]  inc = _GEN_0 + 9'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:382:92, :417:25, :418:25
    automatic logic [85:0] _GEN_1 = {63'h0, _full_adder_io_out_s[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:390:28, :420:{38,56}
    automatic logic        _innermux_exp_true_T_2 = red == 9'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:417:25, :423:137
    automatic logic        _innermux_exp_false_T_2 = inc > 9'hFE;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:61, :418:25, :424:98
    norm_out_frac_r <=
      diff_sign
        ? (_full_adder_io_out_s[23]
             ? _GEN_1
             : red[8] | _innermux_exp_true_T_2 ? 86'h0 : _GEN_1 << _LZC32_2_io_out_c)
        : {63'h0,
           _full_adder_io_out_c
             ? (inc[8] | _innermux_exp_false_T_2
                  ? 23'h7FFFFF
                  : _full_adder_io_out_s[23:1])
             : _full_adder_io_out_s[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:387:48, :390:28, :408:26, :417:25, :418:25, :420:{38,56}, :423:{47,62,114,118,129,137}, :424:{48,75,79,90,98,134}, :429:{39,43}
    norm_out_exp <=
      diff_sign
        ? (_full_adder_io_out_s[23]
             ? ref_exp
             : red[8] | _innermux_exp_true_T_2 ? 8'h1 : red[7:0])
        : _full_adder_io_out_c
            ? (inc[8] | _innermux_exp_false_T_2 ? 8'hFE : inc[7:0])
            : ref_exp;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:385:36, :387:48, :390:28, :417:25, :418:25, :423:{62,118,137}, :424:{79,98}, :425:{46,94,109,141}, :426:{47,74,89,121}, :434:{37,41}
    norm_out_sign <=
      diff_sign
      & (_exp_subtractor_io_out_c
           ? ~_exp_subtractor_io_out_s + 8'h1
           : _exp_subtractor_io_out_s) < 8'h18 & ~_full_adder_io_out_c
      ^ (_GEN ? io_in_b[31] : io_in_a[31]);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:328:25, :329:25, :363:32, :382:{41,67,92,116}, :383:41, :386:37, :387:48, :390:28, :402:{37,80}, :423:137, :438:38
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
      automatic logic [31:0] _RANDOM[0:2];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
        end	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
        norm_out_frac_r = {_RANDOM[2'h0], _RANDOM[2'h1], _RANDOM[2'h2][21:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9, :429:39
        norm_out_exp = _RANDOM[2'h2][29:22];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9, :429:39, :434:37
        norm_out_sign = _RANDOM[2'h2][30];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9, :429:39, :438:38
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  full_subtractor exp_subtractor (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:363:32
    .io_in_a  (exp_wire_0),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:333:68, :334:19, :335:42
    .io_in_b  (exp_wire_1),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:340:68, :341:19, :342:42
    .io_out_s (_exp_subtractor_io_out_s),
    .io_out_c (_exp_subtractor_io_out_c)
  );
  full_adder_4 full_adder (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:390:28
    .io_in_a  ({1'h1, _GEN ? io_in_b[22:0] : io_in_a[22:0]}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:291:16, :350:25, :351:25, :383:41, :440:34
    .io_in_b  (diff_sign ? ~fracadd_in_b + 24'h1 : fracadd_in_b),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:384:41, :387:48, :392:{27,47,69}
    .io_out_s (_full_adder_io_out_s),
    .io_out_c (_full_adder_io_out_c)
  );
  LZC32_2 LZC32_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:408:26
    .io_in_d  ({_full_adder_io_out_s, 8'hFF}),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:390:28, :409:{35,82}
    .io_out_c (_LZC32_2_io_out_c)
  );
  assign io_out_s = {norm_out_sign, norm_out_exp, norm_out_frac_r[22:0]};	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\FPPackageMario\\FP_Modules\\FPUnits.scala:288:9, :429:39, :432:30, :434:37, :438:38, :441:47
endmodule

module doublex_axpy(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:70:7
  input         clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:70:7
                reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:70:7
  input  [31:0] io_in_complex_1_0_Re,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_in_complex_1_0_Im,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_in_complex_2_0_Re,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_in_complex_2_0_Im,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_in_scalar_1,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_in_scalar_2,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
  output [31:0] io_out_axpy_0_Re,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
                io_out_axpy_0_Im	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:72:15
);

  wire [31:0] _FP_mult_32_1_v2_3_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:102:31
  wire [31:0] _FP_mult_32_1_v2_2_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:95:31
  wire [31:0] _FP_mult_32_1_v2_1_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:89:31
  wire [31:0] _FP_mult_32_1_v2_io_out_s;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:83:31
  FP_mult_32_1_v2 FP_mult_32_1_v2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:83:31
    .clock    (clock),
    .io_in_a  (io_in_complex_1_0_Re),
    .io_in_b  (io_in_scalar_1),
    .io_out_s (_FP_mult_32_1_v2_io_out_s)
  );
  FP_mult_32_1_v2 FP_mult_32_1_v2_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:89:31
    .clock    (clock),
    .io_in_a  (io_in_complex_1_0_Im),
    .io_in_b  (io_in_scalar_1),
    .io_out_s (_FP_mult_32_1_v2_1_io_out_s)
  );
  FP_mult_32_1_v2 FP_mult_32_1_v2_2 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:95:31
    .clock    (clock),
    .io_in_a  (io_in_complex_2_0_Re),
    .io_in_b  (io_in_scalar_2),
    .io_out_s (_FP_mult_32_1_v2_2_io_out_s)
  );
  FP_mult_32_1_v2 FP_mult_32_1_v2_3 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:102:31
    .clock    (clock),
    .io_in_a  (io_in_complex_2_0_Im),
    .io_in_b  (io_in_scalar_2),
    .io_out_s (_FP_mult_32_1_v2_3_io_out_s)
  );
  FP_add_32_1 FP_add_32_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:110:26
    .clock    (clock),
    .io_in_a  (_FP_mult_32_1_v2_io_out_s),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:83:31
    .io_in_b  (_FP_mult_32_1_v2_2_io_out_s),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:95:31
    .io_out_s (io_out_axpy_0_Re)
  );
  FP_add_32_1 FP_add_32_1_1 (	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:117:26
    .clock    (clock),
    .io_in_a  (_FP_mult_32_1_v2_1_io_out_s),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:89:31
    .io_in_b  (_FP_mult_32_1_v2_3_io_out_s),	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:102:31
    .io_out_s (io_out_axpy_0_Im)
  );
endmodule

