// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module pp_controller(	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
  input          clock,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
                 reset,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
  output         io_in_en_tr,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_in_en_d0,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_in_en_d1,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  input  [127:0] io_ug_in,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output         io_addra_tr,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output [31:0]  io_wea_tr,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_wea_d0,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_wea_d1,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output [127:0] io_dina_tr,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_dina_d0,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output         io_addra_d0,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output [127:0] io_dina_d1,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  output         io_addra_d1,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_tsqr_en,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
  input          io_mem0_fi,	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
                 io_mem1_fi	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:235:15
);

  reg        first_cycle_tr;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:275:31
  reg        first_cycle_d1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31
  reg        d0_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:277:25
  reg        d1_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:278:25
  reg  [1:0] addr_counter;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29
  wire       _GEN = d1_cycle & io_mem1_fi;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:278:25, :299:23
  wire       _GEN_0 = d0_cycle & io_mem0_fi;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:277:25, :310:23
  wire       _GEN_1 = first_cycle_tr | _GEN;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:275:31, :286:23, :289:17, :299:{23,38}, :301:17, :310:37
  wire       _GEN_2 = _GEN | ~_GEN_0 & first_cycle_d1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:270:14, :276:31, :286:23, :299:{23,38}, :302:17, :310:{23,37}, :312:17, :323:29
  wire       _GEN_3 = first_cycle_tr | _GEN | _GEN_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:275:31, :276:31, :286:23, :299:{23,38}, :310:{23,37}, :323:29
  always @(posedge clock) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
    if (reset) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      first_cycle_tr <= 1'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31
      first_cycle_d1 <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :276:31
      d0_cycle <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :277:25
      d1_cycle <= 1'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :278:25
      addr_counter <= 2'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29
    end
    else begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      automatic logic _GEN_4;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31, :323:29, :330:42, :331:22
      _GEN_4 = first_cycle_d1 & (&addr_counter);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31, :279:29, :293:23, :323:29, :330:42, :331:22
      first_cycle_tr <= ~(first_cycle_tr & (&addr_counter)) & first_cycle_tr;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:275:31, :279:29, :286:23, :293:{23,42}, :294:22
      first_cycle_d1 <= (_GEN_3 | ~_GEN_4) & first_cycle_d1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31, :286:23, :299:38, :310:37, :323:29, :330:42, :331:22
      if (first_cycle_tr) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:275:31
        d1_cycle <= (&addr_counter) | d1_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:278:25, :279:29, :293:{23,42}, :295:16
        addr_counter <= addr_counter + 2'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29, :292:34
      end
      else if (_GEN) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:299:23
        d0_cycle <= (&addr_counter) | d0_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:277:25, :279:29, :293:23, :306:42, :308:16
        d1_cycle <= ~(&addr_counter) & d1_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:278:25, :279:29, :293:23, :306:42, :307:16
        addr_counter <= addr_counter + 2'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29, :292:34, :305:34
      end
      else begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:299:23
        if (_GEN_0) begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:310:23
          d0_cycle <= ~(&addr_counter) & d0_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:277:25, :278:25, :279:29, :293:23, :306:42, :307:16, :317:42, :319:16
          addr_counter <= addr_counter + 2'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29, :292:34, :316:34
        end
        else begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:310:23
          d0_cycle <= _GEN_4 | d0_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31, :277:25, :323:29, :330:42, :331:22, :332:16
          if (first_cycle_d1)	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:276:31
            addr_counter <= addr_counter + 2'h1;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:279:29, :292:34, :329:34
        end
        d1_cycle <= _GEN_0 & (&addr_counter) | d1_cycle;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:278:25, :279:29, :293:23, :310:{23,37}, :317:42, :318:16
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
    `ifdef FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      `FIRRTL_BEFORE_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      automatic logic [31:0] _RANDOM[0:0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      `ifdef INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
        `INIT_RANDOM_PROLOG_	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
        first_cycle_tr = _RANDOM[/*Zero width*/ 1'b0][0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31
        first_cycle_d1 = _RANDOM[/*Zero width*/ 1'b0][1];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31, :276:31
        d0_cycle = _RANDOM[/*Zero width*/ 1'b0][2];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31, :277:25
        d1_cycle = _RANDOM[/*Zero width*/ 1'b0][3];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31, :278:25
        addr_counter = _RANDOM[/*Zero width*/ 1'b0][5:4];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31, :279:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
      `FIRRTL_AFTER_INITIAL	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_en_tr = first_cycle_tr;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31
  assign io_in_en_d0 = ~_GEN_1 & _GEN_0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :286:23, :289:17, :299:38, :301:17, :310:{23,37}
  assign io_in_en_d1 = ~first_cycle_tr & _GEN_2;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :275:31, :286:23, :288:17, :299:38, :302:17, :310:37
  assign io_addra_tr = first_cycle_tr & addr_counter[0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :261:15, :275:31, :279:29, :286:23, :290:17
  assign io_wea_tr = 32'hFFFFFFFF;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :280:19
  assign io_wea_d0 = 32'hFFFFFFFF;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :280:19
  assign io_wea_d1 = 32'hFFFFFFFF;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :280:19
  assign io_dina_tr = first_cycle_tr ? io_ug_in : 128'h0;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :269:14, :275:31, :286:23, :291:16
  assign io_dina_d0 = _GEN_1 | ~_GEN_0 ? 128'h0 : io_ug_in;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :269:14, :270:14, :286:23, :289:17, :299:38, :301:17, :310:{23,37}
  assign io_addra_d0 = ~_GEN_1 & _GEN_0 & addr_counter[0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :262:15, :279:29, :286:23, :289:17, :290:17, :299:38, :301:17, :310:{23,37}
  assign io_dina_d1 =
    first_cycle_tr | ~(_GEN | ~(_GEN_0 | ~first_cycle_d1)) ? 128'h0 : io_ug_in;	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :269:14, :271:14, :275:31, :276:31, :286:23, :299:{23,38}, :304:16, :310:{23,37}, :323:29
  assign io_addra_d1 = ~first_cycle_tr & _GEN_2 & addr_counter[0];	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :263:15, :275:31, :279:29, :286:23, :288:17, :290:17, :299:38, :302:17, :310:37
  assign io_tsqr_en = ~_GEN_3 & first_cycle_d1 & (&addr_counter);	// C:\\TRIG-PREPROCESSING\\Pre-TSQR\\src\\main\\scala\\Preprocessor.scala:234:7, :272:14, :276:31, :279:29, :286:23, :293:23, :299:38, :310:37, :323:29
endmodule

