#!/bin/csh -f
################################################################################
# simulation top mcript
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim mcript dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+SINGLE_CORE\
     +define+ST_WIDTH_8\
     +define+ST8_RANDOM_TEST_8X4\
     -f ../filelist/filelist_st8_1c.f  
     #+define+ST16_RANDOM_TEST_16X8\
     #+define+ST16_RANDOM_TEST_24X8\
     #+define+ST16_RANDOM_TEST_32X8\

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim -voptargs=+acc=npr work.tsqr_mc_st8_tb -t 1ns

###################################### mus  ####################################
add wave -position insertpoint /tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/simple_dual_19_2/ram_ext/Memory

add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/clk        
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/rst        
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/tsqr_en    
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/tile_no    
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/*  


add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/*
  
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/pp/*

add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/simple_dual_19/ram
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/simple_dual_19_2/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/simple_dual_19_1/ram


add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/fsms_0/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/_yj_reg_vec_0_T_1 
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/_yj_reg_vec_1_T_2 
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/yj_reg_vec_0 
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/yj_reg_vec_1 
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/yj0 

#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/*

add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/FP_DDOT_dp_complex_19/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/FP_sqrt_32_23/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/FP_square_root_newfpu_19/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr5_complex_19/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr5_complex_19/FPComplexMult_v2_19_1/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/FPComplexMult_v2_19/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr5_complex_19/FP_square_root_newfpu_19/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/yj_reg_vec_0 
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/yj_reg_vec_1 


add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr7_19/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/axpy_dp_complex_19/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/FP_DDOT_dp_complex_19/FPComplexAdder_v2_19/*
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr5_complex_19/FP_divider_32_15_io_in_a
#add wave -noupdate -format logic -hexadecimal tsqr_mc_st4_tb/u_tsqr_st8_1c/hh_core/u_hh_datapath/hqr5_complex_19/FP_divider_32_15_1_io_in_a
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/simple_dual_19_2/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/simple_dual_19_1/*
add wave -noupdate -format logic -hexadecimal tsqr_mc_st8_tb/u_tsqr_st8_1c/hh_core/simple_dual_19/*

run 35 us                                                                            

